# Since we need to run part of your test suite, most libraries will first
# need to install vendors, for example via composer.
before_commands:
    - composer install --dev

tools:
    php_code_coverage: true