filter:
  excluded_paths: [tests/*]

build:
  nodes:
    coverage:
      tests:
        override:
          - command: vendor/bin/phpunit --verbose --coverage-text --coverage-clover=coverage.clover
            coverage:
              file: coverage.clover
              format: clover